### PR TITLE
Added missing colspan parameter to setCell method.

### PR DESCRIPTION
**Pull request by mehmetbektas**
Missing parameter that is necessary to merge cells is added to setCell metod.

### CODE REVIEW

**Comment by hnb13686** [comment]
What is needed for this to be merged back in. Sorry new to this system so not sure if its just waiting for someone with write access to merge the change or something else.

**Comment by hnb13686** [comment]
Thank you guys. I also was adding rowspan and update sample file to demonstrate the use. Can you tell me what is the process to follow to do it in the community?

**Comment by josesegarra** [comment]
Sorry...being busy on other projects and I wasn't paying enough attention to this one. Added you as collaborator. You should be able to commit code.

**Comment by bkskomal** [comment]
I want to apply different styles inside single cell.

**Pull request merged**
