### PR TITLE
Added Merge cells support

### PR DESCRIPTION
**Pull request by Gabrielpanga**

### CODE REVIEW

**Comment by josesegarra** [comment]
Thanks Gabriel !!!

**Comment by buzkanlamaca** [comment]
I have updated myexcel.js, but i can not overcome how to use it. I mean if i want to merge cells A3 to B3 what piece of code i must use? thanks a lot..

**Comment by thaison316** [comment]
how to use this?  can someone help me?

**Comment by Gabrielpanga** [comment]
Hello @thaison316 ,

What i have done is to add support for a cell to be combine to the cells that are next to each other, not between rows.

I have reviewed the functionallity and seems i haven't replicate my version to the project. Im submitting a fix and adding an example so you can check it out.
https://github.com/jsegarra1971/MyExcel/pull/35

Regards

**Comment by thaison316** [comment]
Thank you so much for responding

**Pull request merged**
